### ISSUE TITLE
[Error] Spark 로컬 환경 내 분산 파일 저장

### ISSUE THREAD

**Issue by soobeen-byul** [oppenheimer-joa/spark#6]
안녕하세요. spark팀 수빈, 주헌 입니다.

spark job 실행 시, 에러가 발생하고 있으며 해당 발생 에러가 발생하는 이유는 다음과 같습니다. 

### error
```
Caused by: java.io.FileNotFoundException: File file:/home/ubuntu/spark/spark-3.2.4/test/datas/temp_KOPIS_2023-09-04.parquet/_temporary/0 does not exist
        at org.apache.hadoop.fs.RawLocalFileSystem.listStatus(RawLocalFileSystem.java:597)
        at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1972)
        at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:2014)
        at org.apache.hadoop.fs.ChecksumFileSystem.listStatus(ChecksumFileSystem.java:761)
        at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1972)
        at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:2014)
        at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.getAllCommittedTaskPaths(FileOutputCommitter.java:334)
        at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.commitJobInternal(FileOutputCommitter.java:404)
        at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.commitJob(FileOutputCommitter.java:377)
        at org.apache.parquet.hadoop.ParquetOutputCommitter.commitJob(ParquetOutputCommitter.java:48)
        at org.apache.spark.internal.io.HadoopMapReduceCommitProtocol.commitJob(HadoopMapReduceCommitProtocol.scala:182)
        at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$write$21(FileFormatWriter.scala:250)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at org.apache.spark.util.Utils$.timeTakenMs(Utils.scala:634)
        at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:250)
        ... 42 more
```
### 원인

아래 코드를 기반으로 로컬에 파일 저장 시, 해당 파일이 worker에 분산 저장되는 과정에서 오류 발생

```
output_path = f"/home/ubuntu/spark/spark-3.2.4/test/datas/temp_KOPIS_{date}.parquet"
json_df.write.parquet(output_path)
```

### 참고사항

로컬 파일 시스템 대신 **HDFS** 또는 **S3**와 같은 분산 파일 시스템을 사용하는 것이 스파크와 더욱 호환성이 높으므로, 스파크 클러스터를 운영하는 환경에서는 **분산 파일 시스템을 권장함**

**Comment by soobeen-byul** [comment]
## 시도  1 - buffer

### 1-1. df.to_parquet()

- source
```
out_buffer = io.BytesIO()
json_df.to_csv(out_buffer)

s3.put_object(Bucket='sms-basket', key = output_path, Body = out_buffer.getvalue())
```

- error

```
AttributeError: 'DataFrame' object has no attribute 'to_parquet'
```


---

### 1-2. df.write.parquet()
1-1의 오류 확인 후 **to_parquet() → write.parquet()** 변경하여 2차 시도

- source
```
out_buffer = io.BytesIO()
json_df.write.parquet(out_buffer)

s3.put_object(Bucket='sms-basket', key = output_path, Body = out_buffer.getvalue())
```
- error
```
py4j.protocol.Py4JError: An error occurred while calling o37.parquet. Trace: py4j.Py4JException: Method parquet([class java.util.ArrayList]) does not exist 
```
- reference : [ref](https://stackoverflow.com/questions/53416226/how-to-write-parquet-file-from-pandas-dataframe-in-s3-in-python)

### 1-3. toPandas() 변환 후 저장 ⭐

아래 주헌님 코드를 참고하여 1-1의 오류가 pandas dataframe 형식이 아님에 따라 발생한다고 판단되어 변환 후 buffer 저장 및 s3 업로드 진행하였습니다. 

```
json_df = spark.read.json(transformed_rdd)

out_buffer = io.BytesIO()
pdf = json_df.toPandas()
pdf.to_parquet(out_buffer)

s3 =  create_s3client()

output_path = f'test-spark/KOPIS_{date}.parquet'
s3.put_object(Bucket='sms-basket', Key = output_path, Body = out_buffer.getvalue())
```

- 파일 확인

s3에 업로드된 파일은 읽어온 결과, 아래와 같이 parquet 형식임을 확인하였으나 아래 논의점에 대한 회의가 필요할 것으로 보입니다.

```
df=pq.read_pandas('KOPIS_2023-09-04.parquet',columns=['mt20id','prfnm'])
print(df)

pyarrow.Table
mt20id: string
prfnm: string
----
mt20id: [["PF224855","PF224873","PF224877","PF224878","PF224939","PF224962","PF224969","PF224983","PF224996","PF225000"]]
prfnm: [["김종규 지휘자와 함께하는 뮤지컬의 밤, 캣츠편","돌아온다 [김해]","제25회 최훈차콰이어 정기연주회","하녀들 [부산]","MODAFE, Center Stage of Seoul","굿데이남성중창단, Awesome 콘서트","Woodstock Music & Art Fair","히사이시 조 & 지브리 영화 음악 콘서트, Film Music & His Own Music [서울(앵콜)] (9.29)","제네다, 인생은 영화처럼 [안성]","브런치 콘서트
, 두 남자와 떠나는 피아노 여행"]]
```

```
pdf=pq.read_pandas('KOPIS_2023-09-04.parquet').toPandas()
pdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 20 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   dtguidance    10 non-null     object
 1   entrpsnm      10 non-null     object
 2   fcltynm       10 non-null     object
 3   genrenm       10 non-null     object
 4   mt10id        10 non-null     object
 5   mt20id        10 non-null     object
 6   openrun       10 non-null     object
 7   pcseguidance  10 non-null     object
 8   poster        10 non-null     object
 9   prfage        10 non-null     object
 10  prfcast       10 non-null     object
 11  prfcrew       10 non-null     object
 12  prfnm         10 non-null     object
 13  prfpdfrom     10 non-null     object
 14  prfpdto       10 non-null     object
 16  prfstate      10 non-null     object
 17  sty           10 non-null     object
 18  styurls       10 non-null     object
 19  tksites       10 non-null     object

```

**Comment by blahxblah** [comment]
## bytesIO, pyarrow, pandas 모듈 이용


```python
 # dataframe 은 spark dataframe 형식
 pandas_df = dataframe.toPandas()
    
    table = pa.Table.from_pandas(pandas_df)
    
    buffer = BytesIO()
    with buffer:
        with pq.ParquetWriter(buffer, table.schema) as writer:
            writer.write_table(table)
        parquet_data = buffer.getvalue()
        
    # 로컬 저장 경로 - Parquet 파일로 저장 - 경로 설정 필요
#    dataframe.write.parquet(f'file://{local_path}')

    # s3 저장 경로 - spark/kobis/2023 - 경로 설정 필요
    parquet_path = f'spark/kobis/{year}'
    
    # S3 업로드
    s3 = create_s3client()
    s3.put_object(Bucket='sms-basket', Key=f'{parquet_path}/{filename}.parquet', Body=parquet_data)
```

## 논의
- parquet 로 저장이 되기는 하지만 spark 로직을 통한 parquet 저장형태가 아닙니다. spark의 데이터 분산 처리, 변환 과정에 대한 이득을 볼 수 있는 형태인지 불분명합니다.
- Hadoop 환경을 구성하지 않은 spark 단독 구성에서 aws s3와의 연동을 위해 boto3 모듈을 사용하고 있습니다. 이 과정에서 spark 로직이 아닌 python 로직이 많이 포함되어 있으며 spark 를 활용해야 하는 당위성이 줄어드는 느낌입니다.
- s3a connector를 활용해서 조금 더 완전한 spark 스크립트를 작성하는 게 좋을 지 고민입니다.

## spark 단독 설정 시 s3a connector 연결 by chatGPT
Hadoop의 S3A 커넥터는 Hadoop의 일부 라이브러리와 AWS SDK 라이브러리에 의존합니다. 따라서 이 커넥터를 사용하기 위해 해당 라이브러리들을 설치해야 합니다. 

스파크에서 S3A 커넥터를 사용하기 위해 필요한 Hadoop 서브셋을 설치하는 기본 단계는 다음과 같습니다:

1. **Hadoop AWS 라이브러리 다운로드**
    - 먼저 Maven Repository에서 필요한 버전의 `hadoop-aws` 라이브러리를 찾습니다.
    - [Maven Central Repository](https://search.maven.org/)에서 "hadoop-aws"를 검색하여 필요한 버전의 jar 파일을 다운로드합니다.

2. **AWS Java SDK 다운로드**
    - 동일한 Maven Repository에서 `aws-java-sdk`를 검색하여 호환되는 버전의 jar 파일을 다운로드합니다.

3. **JAR 파일을 Spark 라이브러리 디렉토리로 이동**
    - 다운로드한 두 JAR 파일을 Spark의 `jars` 디렉토리(예: `$SPARK_HOME/jars/`)로 이동합니다.

4. **PySpark 실행 시 JAR 파일 포함**
    - 아래와 같이 PySpark를 실행하여 추가한 JAR 파일들을 포함시킵니다:
      ```bash
      $SPARK_HOME/bin/pyspark --jars $SPARK_HOME/jars/hadoop-aws-<version>.jar,$SPARK_HOME/jars/aws-java-sdk-<version>.jar
      ```

5. **S3A 설정**
    - Spark 설정에서 다음과 같이 S3A 관련 설정을 추가할 수 있습니다:
      ```python
      spark = SparkSession.builder \
                          .appName("S3A with Spark") \
                          .config("spark.hadoop.fs.s3a.access.key", "YOUR_ACCESS_KEY") \
                          .config("spark.hadoop.fs.s3a.secret.key", "YOUR_SECRET_KEY") \
                          .config("spark.hadoop.fs.s3a.impl", "org.apache.hadoop.fs.s3a.S3AFileSystem") \
                          .config('spark.hadoop.fs.s3a.aws.credentials.provider', org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider')
                          .getOrCreate()
      ```

위 단계를 따라 Hadoop의 전체 배포판을 설치하지 않고도 Spark에서 S3A 커넥터를 사용하여 S3와 상호 작용할 수 있습니다.
-

**Comment by soobeen-byul** [comment]
## s3a connector로 파일 읽기 및 쓰기
```
# 데이터 프레임을 Parquet 파일로 저장
df.write.parquet("s3a://your-s3-bucket/path/to/your-data.parquet")

# Parquet 파일을 읽기
df = spark.read.parquet("s3a://your-s3-bucket/path/to/your-data.parquet")
```

**Comment by blahxblah** [comment]
## Spark dataframe을 Pandas dataframe으로 변환 후 로컬 csv 로 내리는 작업 테스트 - EC2 SPARK MASTER

```python
dataframe = dataframe.orderBy("areaCd", "rank")
parquet_path = f's3a://sms-basket/spark/kobis/{year}'
dataframe.toPandas().to_csv('/home/ubuntu/spark/spark-3.2.4/test.csv')
```
- 결과 : 정상적으로 내려짐
```
,areaCd,rnum,rank,rankInten,rankOldAndNew,movieCd,movieNm,openDt,salesAmt,salesShare,salesInten,salesChange,salesAcc,audiCnt,audiInten,audiChange,audiAcc,scrnCnt,showCnt
0,0105001,1,1,0,OLD,20226431,오펜하이머,2023-08-15,103670326,34.1,-247664299,-70.5,10071405252,9125,-21542,-70.2,896563,209,629
1,0105001,2,2,0,OLD,20204264,콘크리트 유토피아,2023-08-09,43398480,14.3,-96852646,-69.1,8430957005,4556,-9561,-67.7,839734,155,467
2,0105001,3,3,0,OLD,20233014,타겟,2023-08-30,39396839,12.9,-94082398,-70.5,610357523,4251,-8661,-67.1,63541,140,462
3,0105001,4,4,0,OLD,20226500,달짝지근해: 7510,2023-08-15,35562505,11.7,-71989554,-66.9,2261034929,3658,-6846,-65.2,227545,126,357
4,0105001,5,5,0,OLD,20228930,엘리멘탈,2023-06-14,19615294,6.4,-35146099,-64.2,18875370357,2132,-3285,-60.6,1860785,63,94
5,0105001,6,6,0,OLD,20218541,밀수,2023-07-26,14653635,4.8,-26240971,-64.2,10554475821,1516,-2527,-62.5,1065951,92,174
6,0105001,7,7,2,OLD,20223831,스파이 코드명 포춘,2023-08-30,6567434,2.2,-10601994,-61.7,112729668,693,-975,-58.5,11941,73,132
7,0105001,8,8,0,OLD,20233075,신체모음.zip,2023-08-30,4281800,1.4,-12581400,-74.6,82615700,409,-1508,-78.7,9570,32,61
8,0105001,9,9,5,OLD,20231413,한 남자,2023-08-30,2500300,0.8,-2305900,-48,58613750,275,-251,-47.7,6038,25,50
9,0105001,10,10,2,OLD,20232740,바비,2023-07-19,2645879,0.9,-3544672,-57.3,2751751188,267,-314,-54,272083,19,23
10,0105002,1,1,0,OLD,20226431,오펜하이머,2023-08-15,59452279,24.7,-191892424,-76.3,8008427802,5833,-17339,-74.8,752737,284,808
11,0105002,2,2,1,OLD,20233014,타겟,2023-08-30,46870313,19.5,-103673811,-68.9,624390782,4934,-9757,-66.4,65154,237,804
12,0105002,3,3,1,OLD,20226500,달짝지근해: 7510,2023-08-15,40801845,17.0,-100714269,-71.2,2850733179,4273,-9686,-69.4,288029,225,660
13,0105002,4,4,-2,OLD,20204264,콘크리트 유토피아,2023-08-09,38916282,16.2,-110516014,-74,9386810944,4174,-10810,-72.1,953354,243,727
14,0105002,5,5,0,OLD,20228930,엘리멘탈,2023-06-14,15797125,6.6,-63939057,-80.2,19285391928,1672,-6232,-78.8,1947239,109,177
15,0105002,6,6,0,OLD,20218541,밀수,2023-07-26,15500548,6.5,-30972356,-66.6,12551400560,1645,-2969,-64.3,1283776,159,278
16,0105002,7,7,0,OLD,20233075,신체모음.zip,2023-08-30,6060700,2.5,-17173000,-73.9,86769500,607,-1886,-75.7,9485,64,131
17,0105002,8,8,0,OLD,20223831,스파이 코드명 포춘,2023-08-30,4779477,2.0,-11016250,-69.7,85686565,503,-1010,-66.8,9266,106,167
18,0105002,9,9,0,OLD,20232629,마야 3: 숲속 왕국의 위기,2023-08-24,2584000,1.1,-7634100,-74.7,80864900,321,-762,-70.4,9295,27,27
19,0105002,10,10,2,OLD,20231413,한 남자,2023-08-30,1402150,0.6,-1239050,-46.9,14345350,163,-121,-42.6,1736,33,53
```

## Spark dataframe을 s3a connector를 이용해서 spark.write.parquet 메소드로 s3에 직접 업로드 테스트 - EC2 SPARK MASTER

```python
dataframe = dataframe.orderBy("areaCd", "rank")
# s3 저장 경로 - spark/kobis/2023 - 경로 설정 필요
parquet_path = f's3a://sms-basket/spark/kobis/{year}'
#dataframe.toPandas().to_csv('/home/ubuntu/spark/spark-3.2.4/test.csv')
dataframe.write.parquet(f'{parquet_path}/{filename}')
```

- 결과 : 로컬에 spark.write.parquet로 저장하는 것과 마찬가지로 s3에 직접 저장할 때도 temp 디렉토리를 생성하면서 오류가 발생합니다. 
```bash
23/09/08 01:25:23 WARN TaskSetManager: Lost task 0.0 in stage 88.0 (TID 408) (172.31.46.252 executor 0): org.apache.spark.SparkException: Task failed while writing rows.
----
Caused by: java.nio.file.AccessDeniedException: delete on s3a://sms-basket/spark/kobis/2023/20230904_boxOffice/_temporary/0/_temporary/attempt_202309080125191490003024444830249_0088_m_000000_408: com.amazonaws.services.s3.model.MultiObjectDeleteException: One or more objects could not be deleted (Service: null; Status Code: 200; Error Code: null; Request ID: M4GAM30F7E54N3TH; S3 Extended Request ID: KDBnMDxZHtyP5M00LtG+nlUgCN6kV4JP06BQmixsuInGOqotJQrbBDzhBu96GlBjgmkHXle+YfM=; Proxy: null), S3 Extended Request ID: KDBnMDxZHtyP5M00LtG+nlUgCN6kV4JP06BQmixsuInGOqotJQrbBDzhBu96GlBjgmkHXle+YfM=:null: AccessDenied: spark/kobis/2023/20230904_boxOffice/_temporary/0/_temporary/attempt_202309080125191490003024444830249_0088_m_000000_408/part-00000-d1260fa1-a224-4638-8067-39a9ce140a82-c000.snappy.parquet: Access Denied
----
Caused by: com.amazonaws.services.s3.model.MultiObjectDeleteException: One or more objects could not be deleted (Service: null; Status Code: 200; Error Code: null; Request ID: M4GAM30F7E54N3TH; S3 Extended Request ID: KDBnMDxZHtyP5M00LtG+nlUgCN6kV4JP06BQmixsuInGOqotJQrbBDzhBu96GlBjgmkHXle+YfM=; Proxy: null), S3 Extended Request ID: KDBnMDxZHtyP5M00LtG+nlUgCN6kV4JP06BQmixsuInGOqotJQrbBDzhBu96GlBjgmkHXle+YfM=
----
23/09/08 01:25:25 INFO DAGScheduler: ResultStage 88 (parquet at NativeMethodAccessorImpl.java:0) failed in 6.518 s due to Job aborted due to stage failure: Task 0 in stage 88.0 failed 4 times, most recent failure: Lost task 0.3 in stage 88.0 (TID 411) (172.31.46.252 executor 0): org.apache.spark.SparkException: Task failed while writing rows.
----
```

## 원인 예측
- 로컬로 저장하든 s3에 바로 저장하든 spark.write.parquet 메소드를 사용했을 때 같은 오류가 발생하는 것으로 보아 s3a connector의 문제는 아닌 듯 합니다.
- 그래서 spark master에서 worker 간의 쓰기, 수정 권한에서 access denied 문제가 있지 않나 예상합니다.

**Comment by blahxblah** [comment]
## 이슈 해결

- Caused by: com.amazonaws.services.s3.model.MultiObjectDeleteException 의 문제를 해결하기 위해 파이썬 코드의 SparkSession에
```python
.config("spark.hadoop.fs.s3a.multiobjectdelete.enable", "false") \
```
위의 옵션을 주었습니다. 그 결과
```bash
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 1HJ1PX39JC2FVV5P; S3 Extended Request ID: qV+O/eGoDulSEaMyqFjCJEM9SucU9eLU4oGGtXV4TJB2uA6MVVa3+2ABscm6vGgLz1dp4B73pkA=; Proxy: null), S3 Extended Request ID: qV+O/eGoDulSEaMyqFjCJEM9SucU9eLU4oGGtXV4TJB2uA6MVVa3+2ABscm6vGgLz1dp4B73pkA=
```
이런 오류 메시지가 나왔고 ROOT계정으로 설정되어 있던 AWS ACCESS KEY 와 AWS SECRET KEY를 IAM 계정으로 바꾸었습니다. 그 결과

![image](https://github.com/oppenheimer-joa/spark/assets/10733724/6a81cc77-898e-4b41-91f5-d1fe36f203d8)

```bash
+-------+----+----+---------+-------------+--------+------------------------+----------+---------+----------+----------+-----------+-----------+-------+---------+----------+-------+-------+-------+
| areaCd|rnum|rank|rankInten|rankOldAndNew| movieCd|                 movieNm|    openDt| salesAmt|salesShare|salesInten|salesChange|   salesAcc|audiCnt|audiInten|audiChange|audiAcc|scrnCnt|showCnt|
+-------+----+----+---------+-------------+--------+------------------------+----------+---------+----------+----------+-----------+-----------+-------+---------+----------+-------+-------+-------+
|0105001|   1|   1|        0|          OLD|20226431|              오펜하이머|2023-08-15|103670326|      34.1|-247664299|      -70.5|10071405252|   9125|   -21542|     -70.2| 896563|    209|    629|
|0105001|   2|   2|        0|          OLD|20204264|       콘크리트 유토피아|2023-08-09| 43398480|      14.3| -96852646|      -69.1| 8430957005|   4556|    -9561|     -67.7| 839734|    155|    467|
|0105001|   3|   3|        0|          OLD|20233014|                    타겟|2023-08-30| 39396839|      12.9| -94082398|      -70.5|  610357523|   4251|    -8661|     -67.1|  63541|    140|    462|
|0105001|   4|   4|        0|          OLD|20226500|        달짝지근해: 7510|2023-08-15| 35562505|      11.7| -71989554|      -66.9| 2261034929|   3658|    -6846|     -65.2| 227545|    126|    357|
|0105001|   5|   5|        0|          OLD|20228930|                엘리멘탈|2023-06-14| 19615294|       6.4| -35146099|      -64.2|18875370357|   2132|    -3285|     -60.6|1860785|     63|     94|
|0105001|   6|   6|        0|          OLD|20218541|                    밀수|2023-07-26| 14653635|       4.8| -26240971|      -64.2|10554475821|   1516|    -2527|     -62.5|1065951|     92|    174|
|0105001|   7|   7|        2|          OLD|20223831|      스파이 코드명 포춘|2023-08-30|  6567434|       2.2| -10601994|      -61.7|  112729668|    693|     -975|     -58.5|  11941|     73|    132|
|0105001|   8|   8|        0|          OLD|20233075|            신체모음.zip|2023-08-30|  4281800|       1.4| -12581400|      -74.6|   82615700|    409|    -1508|     -78.7|   9570|     32|     61|
|0105001|   9|   9|        5|          OLD|20231413|                 한 남자|2023-08-30|  2500300|       0.8|  -2305900|        -48|   58613750|    275|     -251|     -47.7|   6038|     25|     50|
|0105001|  10|  10|        2|          OLD|20232740|                    바비|2023-07-19|  2645879|       0.9|  -3544672|      -57.3| 2751751188|    267|     -314|       -54| 272083|     19|     23|
|0105002|   1|   1|        0|          OLD|20226431|              오펜하이머|2023-08-15| 59452279|      24.7|-191892424|      -76.3| 8008427802|   5833|   -17339|     -74.8| 752737|    284|    808|
|0105002|   2|   2|        1|          OLD|20233014|                    타겟|2023-08-30| 46870313|      19.5|-103673811|      -68.9|  624390782|   4934|    -9757|     -66.4|  65154|    237|    804|
|0105002|   3|   3|        1|          OLD|20226500|        달짝지근해: 7510|2023-08-15| 40801845|      17.0|-100714269|      -71.2| 2850733179|   4273|    -9686|     -69.4| 288029|    225|    660|
|0105002|   4|   4|       -2|          OLD|20204264|       콘크리트 유토피아|2023-08-09| 38916282|      16.2|-110516014|        -74| 9386810944|   4174|   -10810|     -72.1| 953354|    243|    727|
|0105002|   5|   5|        0|          OLD|20228930|                엘리멘탈|2023-06-14| 15797125|       6.6| -63939057|      -80.2|19285391928|   1672|    -6232|     -78.8|1947239|    109|    177|
|0105002|   6|   6|        0|          OLD|20218541|                    밀수|2023-07-26| 15500548|       6.5| -30972356|      -66.6|12551400560|   1645|    -2969|     -64.3|1283776|    159|    278|
|0105002|   7|   7|        0|          OLD|20233075|            신체모음.zip|2023-08-30|  6060700|       2.5| -17173000|      -73.9|   86769500|    607|    -1886|     -75.7|   9485|     64|    131|
|0105002|   8|   8|        0|          OLD|20223831|      스파이 코드명 포춘|2023-08-30|  4779477|       2.0| -11016250|      -69.7|   85686565|    503|    -1010|     -66.8|   9266|    106|    167|
|0105002|   9|   9|        0|          OLD|20232629|마야 3: 숲속 왕국의 위기|2023-08-24|  2584000|       1.1|  -7634100|      -74.7|   80864900|    321|     -762|     -70.4|   9295|     27|     27|
|0105002|  10|  10|        2|          OLD|20231413|                 한 남자|2023-08-30|  1402150|       0.6|  -1239050|      -46.9|   14345350|    163|     -121|     -42.6|   1736|     33|     53|
+-------+----+----+---------+-------------+--------+------------------------+----------+---------+----------+----------+-----------+-----------+-------+---------+----------+-------+-------+-------+
```
정상적으로 저장이 되는 것을 확인했습니다.

## 원인 예측
- 저희 팀은 hadoop이 없이 spark 단독으로 사용하는 환경이므로 s3와의 통신을 위해서는 s3a connector 라이브러리가 필요합니다.
- 그래서 aws-sdk.jar와 hadoop-aws.jar 파일을 spark의 jars 디렉토리에 저장해서 SparkSession config에서 s3a 연결설정을 합니다.
- 이 2개의 라이브러리가 아마도 root 계정의 s3 버킷 접속을 제한하고 있지 않나 예상합니다.
- 그래서 s3 fullaccess 권한이 있는 IAM 계정의 access, secret key를 사용하니 제대로 작동합니다.
- 계정을 바꾸는 것에 앞서 .config("spark.hadoop.fs.s3a.multiobjectdelete.enable", "false") \ 옵션을 주었었는데 IAM 계정으로 전환한 뒤, 해당 옵션을 삭제해도 정상작동 되었습니다. 
- fs.s3a.multiobjectdelete.enable는 S3A 파일 시스템의 여러 오브젝트 삭제 기능을 활성화/비활성화 하는 설정인데 root계정의 삭제권한이 부여되지 않아서 발생된 오류인 것으로 보입니다.

- Ref : https://programming-workspace.tistory.com/61
